fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    puppet_agent:
      repo: "https://github.com/shubhamshinde360/puppetlabs-puppet_agent.git"
      ref: "v0.0.0"
  forge_modules:
    chocolatey: "puppetlabs/chocolatey"
    java: "puppetlabs/java"
    powershell: "puppetlabs/powershell"
    registry: "puppetlabs/registry"
    stdlib: "puppetlabs/stdlib"
  symlinks:
    java_ks: "#{source_dir}"
