name    'puppetlabs-java_ks'
version '0.0.2'
source 'https://github.com/puppetlabs/puppetlabs-java_ks.git'
author 'puppetlabs'
license 'APL 2.0'
summary 'Manage arbitrary Java keystore files'
description 'Uses a combination of keytool and openssl to manage entries in a Java keystore.'
project_page 'https://github.com/puppetlabs/puppetlabs-java_ks'
